### ISSUE TITLE
System.Net.Http 

### ISSUE THREAD

**Issue by blink1217** [ahwm/GodaddyWrapper.Net#1]
Version conflicts in the System.Net.Http on the latest .NET core in visual studio 2017

**Comment by vip30** [comment]
Sorry, I am not using VS2017.
But I try to download it now and will get back to you soon
Thanks

**Comment by vip30** [comment]
It's fixed.
Can you please try to get the 1.1.0-beta version to test again?
Thanks

Commit cf733c24d00e1b6039ea0936a7a8b138ecc18985 closes #1

**Comment by vip30** [comment]
It's fixed.
Can you please try to get the 1.1.0-beta version from nuget to test again?
Thanks

Commit cf733c24d00e1b6039ea0936a7a8b138ecc18985 closes #1

**Comment by blink1217** [comment]
Thanks that works for me now :)
