### ISSUE TITLE
Wrapper does not work when null values being sent

### ISSUE THREAD

**Issue by Blackcode** [ahwm/GodaddyWrapper.Net#2]
if you try to send null values at https://developer.godaddy.com/doc#!/_v1_domains/recordReplaceTypeName it gives error

fix by changing Line 21 in Helper class "HTTPClientExtensions.cs"

`var jsonString = JsonConvert.SerializeObject(content,new JsonSerializerSettings{NullValueHandling = NullValueHandling.Ignore});`

to avoid null values being sent

**Comment by vip30** [comment]
Thanks for your comment.
You are right.
I have updated that part of code by this commit 3cc996ffa6df4da515e9deaaab171f0ed32ec9d8
and updated the nuget version (The latest version should be 1.1.1-beta)

**Comment by Blackcode** [comment]
I will update my code even if I have to port everything back to .net 4.6  (not using core)
P.S. Thanks for the wrapper, very useful
