### ISSUE TITLE
BulkCheckDomainAvailable not working

### ISSUE THREAD

**Issue by brettsschmidt** [ahwm/GodaddyWrapper.Net#4]
I get a "Bad Request" status code when trying to use the BulkCheckDomainAvailable function. 

How I am using it:
`public static async Task<DomainAvailableBulkResultResponse> CheckDomains(List<CSVData> checkdomains)
       {
            List<string> stdomains = new List<string>();
            foreach(CSVData data in checkdomains)
            {
                stdomains.Add(data.DomainName);
            }
            var client = new Client(Key, Secret, "https://api.godaddy.com/api/v1/");
            try
            {
                var response = await client.BulkCheckDomainAvailable(new DomainAvailableBulk
                {
                    domains = stdomains,
                    checkType = "FAST"
                });
                return response;
            }
            catch (GodaddyException ex)
            {
                Console.WriteLine(ex.ErrorResponse.Message);
                Console.WriteLine(ex.StatusCode);
                return null;
            }
        }`

**Comment by vip30** [comment]
Noted the issue.

However, I currently not used dotnet anymore, I can try to fix it but just need to have some time.

**Comment by vip30** [comment]
https://www.nuget.org/packages/GodaddyWrapper/1.1.2-beta

Please try to use 1.1.2 thanks

**Comment by IQSBrett** [comment]
Is this depreciated for dotnet or do you have another repo for a wrapper on a different framework? I would prefer not to use dotnet if I don't have to.

Thank you so much though.

**Comment by vip30** [comment]
No, just because I have quit my dotnet job. (That's why I will not use godaddy anymore)

So for the further issue, of course you still can report but I don't have any test account ...

**Comment by vip30** [comment]
I think I can close the issue now.
