### ISSUE TITLE
Incorrect work of RetrieveDNSRecordsWithTypeAndName method

### ISSUE THREAD

**Issue by nurlan74** [ahwm/GodaddyWrapper.Net#6]
Hi, seems your code has a bug in the RetrieveDNSRecordsWithTypeAndName method, you double checking the "name" parameter for null value and the second condition will never be running as expected:
            if (Name != null)
            {
                if (Name != null)
                    urlPath = $"domains/{domain}/records/{Type}";
                else
                    urlPath = $"domains/{domain}/records/{Type}/{Name}";
            }

I think the code should be something like that:
            if (string.IsNullOrEmpty(Name))
                urlPath = $"domains/{domain}/records/{Type}";
            else
                urlPath = $"domains/{domain}/records/{Type}/{Name}";

**Comment by vip30** [comment]
Thanks for your report, I guess it is possibly because copy and paste

Will update it later

**Comment by vip30** [comment]
Updated
