### ISSUE TITLE
Updated NuGet Package?

### ISSUE THREAD

**Issue by ahwm** [ahwm/GodaddyWrapper.Net#7]
Any chance of getting an updated NuGet package released? It's been almost 2 years since the last release. And the multi-targeting never made it. I'd be happy to help get that going if you'd be open to that.

**Comment by vip30** [comment]
Sry abt that as I already not develop in dotnet almost 3 years ago

If you want to do something on it just go ahead

Thanks

**Comment by ahwm** [comment]
Okay. Thanks. I’ll get that all set up and let you know if you wouldn’t mind pointing to it. 🙂

**Comment by vip30** [comment]
No problem just let me know if you need any help

**Comment by ahwm** [comment]
I was just thinking it might be nice to transfer ownership of this repo so that stars and watchers get moved over, too. But I mirrored this repo at the URL below.

https://github.com/ahwm/GoDaddy.Net

I'm not sure what would be best for other devs - transferring ownership of the nuget package or just putting up a new one so i put up a new one for now.

https://www.nuget.org/packages/GoDaddy.NET

If you're open to changing ownership of the existing repo and package, I think that would give the best experience overall.

Thanks!

**Comment by vip30** [comment]
already sd out the request pls check it out

**Comment by ahwm** [comment]
Thanks! That will make it easier, I think.
